# SVD : Singular value decomposition

## References

이론

* [wikipedia/Singular value decomposition](https://en.wikipedia.org/wiki/Singular_value_decomposition)
* 공돌이의 수학정리노트
  - [4. 선형대수학 / 10 특이값분해 (SVD)](https://wikidocs.net/25820)
  - [특이값 분해(SVD)의 기하학적 의미와 활용 소개](https://www.youtube.com/watch?v=cq5qlYtnLoY&t=1072s)
* ETC
  - [SVD와 PCA, 그리고 잠재의미분석(LSA)](https://ratsgo.github.io/from%20frequency%20to%20semantics/2017/04/06/pcasvdlsa/)
  - [다크프로그래머/특이값 분해(Singular Value Decomposition, SVD)의 활용](https://darkpgmr.tistory.com/106)
  - [Relationship between SVD and PCA. How to use SVD to perform PCA?](https://stats.stackexchange.com/questions/134282/relationship-between-svd-and-pca-how-to-use-svd-to-perform-pca)
  - [Deep Learning Book Series / 2.8 Singular Value Decomposition](https://hadrienj.github.io/posts/Deep-Learning-Book-Series-2.8-Singular-Value-Decomposition/)
  - [Text Mining 101: A Stepwise Introduction to Topic Modeling using Latent Semantic Analysis (using Python)](https://www.analyticsvidhya.com/blog/2018/10/stepwise-guide-topic-modeling-latent-semantic-analysis/)
  
코드

* [Towards data science/My Notes for Singular Value Decomposition with Interactive Code (feat Peter Mills)](https://towardsdatascience.com/my-notes-for-singular-value-decomposition-with-interactive-code-feat-peter-mills-7584f4f2930a)
  - [codes](https://colab.research.google.com/drive/1iXxVkDRdwSXnkTDllKEupNmfNGIwjyLn)

$$
AV = US
$$

$$
∴ A = USV^T
$$

U와 V는 아래와 같이 되므로 eigen decomposition을 통해 구할 수 있다. 

$$
A^T = (USV^T)^T = VS^TU^T
$$


$$
AA^T = USV^TVS^TU^T = USS^TU^T = US^2U^T
$$

$$
A^TA = VS^2V
$$

가장 위의 식은 아래와 같이 쓸 수 있다. 이것은 $U^T$(m,m)를 $A$(m,n)라는 가중치를 주어 선형변환 하였을 때,$S$(m,n)만큼 길이가 변한 상태에서 $V^T$(n,n)가 존재한다는 의미로 풀이할 수 있다. 

$$
U^TA = SV^T
$$

## 1. Data

In [1]:
import numpy as np

np.random.seed(45)
A = np.random.randn(4, 5) * 10
print(A)

[[  0.26374773   2.60321701  -3.95145542  -2.04300905 -12.71632655]
 [-25.9687863    2.89680912  -8.73304644   3.94072657   9.35105544]
 [ -0.15684708   2.59595966 -14.73314241   8.01926596 -17.50752387]
 [ -4.95051931 -10.08600809   0.25244186  -1.21506855 -15.46873182]]


## 2. Get S, U and V

In [2]:
temp = A.dot(A.T)
eig_value, eig_vector = np.linalg.eig( temp )

U = eig_vector
S = np.diag( np.sqrt( eig_value ) )
V = A.T.dot( U ).dot( np.linalg.inv(S) )


In [3]:
print( "Original Matrix A: \n", A, end="\n\n" )
print( "Created Matrix U: \n", U, end="\n\n" )
print( "Created Matrix S: \n", S, end="\n\n" )
print( "Created Matrix V: \n", V, end="\n\n" )


Original Matrix A: 
 [[  0.26374773   2.60321701  -3.95145542  -2.04300905 -12.71632655]
 [-25.9687863    2.89680912  -8.73304644   3.94072657   9.35105544]
 [ -0.15684708   2.59595966 -14.73314241   8.01926596 -17.50752387]
 [ -4.95051931 -10.08600809   0.25244186  -1.21506855 -15.46873182]]

Created Matrix U: 
 [[ 0.36248623 -0.21169502  0.90742112 -0.01938732]
 [-0.65876953 -0.74318275  0.09134238  0.07320302]
 [ 0.53402233 -0.56792374 -0.35681554 -0.51474796]
 [ 0.38658323 -0.28342062 -0.20230215  0.85399063]]

Created Matrix S: 
 [[30.60369609  0.          0.          0.        ]
 [ 0.         28.67313561  0.          0.        ]
 [ 0.          0.          5.86754412  0.        ]
 [ 0.          0.          0.         14.79497474]]

Created Matrix V: 
 [[ 0.49685183  0.72318133 -0.18325457 -0.40912996]
 [-0.11362943 -0.04602465  0.63756793 -0.66157839]
 [-0.11271581  0.54484822  0.1401972   0.4891364 ]
 [ 0.01555854 -0.23388238 -0.70037853 -0.32696753]
 [-0.85280695  0.35118364 -0.

## 3. Reconstruct

본래 데이터 A와 같은 결과를 얻을 수 있다. 

In [4]:
reconstructed = np.dot( U, S ).dot( V.T )
print( "Original Matrix A: \n", A, end="\n\n" )
print( "ReConstructed Matrix: \n", reconstructed, end="\n\n" )

Original Matrix A: 
 [[  0.26374773   2.60321701  -3.95145542  -2.04300905 -12.71632655]
 [-25.9687863    2.89680912  -8.73304644   3.94072657   9.35105544]
 [ -0.15684708   2.59595966 -14.73314241   8.01926596 -17.50752387]
 [ -4.95051931 -10.08600809   0.25244186  -1.21506855 -15.46873182]]

ReConstructed Matrix: 
 [[  0.26374773   2.60321701  -3.95145542  -2.04300905 -12.71632655]
 [-25.9687863    2.89680912  -8.73304644   3.94072657   9.35105544]
 [ -0.15684708   2.59595966 -14.73314241   8.01926596 -17.50752387]
 [ -4.95051931 -10.08600809   0.25244186  -1.21506855 -15.46873182]]



## 4. Truncated SVD

아래와 같다. $A$(m,n)에 $V$(n,n)라는 가중치를 주어 선형변환시켜 변형시키는 구조이다. 

$U$는 (m,n) 차원의 diagonal matrix이므로, 원하는 (i,i) 차원 만큼만 취하여 $S$와의 내적을 구하면 i차원으로 차원을 축소시키는 효과를 얻을 수 있다. 

$$
AV = US
$$

$$
US → U^\prime S^\prime
$$

![](images/TruncatedSVD.png)

In [5]:
dim = 2
U_prime = U[:, :dim]
S_prime = S[ :dim, :dim ]
V_prime = V[:, :dim]

decomposed1 = np.dot( U_prime , S_prime )
decomposed2 = np.dot( A , V_prime )

In [6]:
print( "Original Matrix A: \n", A, end="\n\n" )
print( "Decomposed Matrix1: \n", decomposed1, end="\n\n" )
print( "Decomposed Matrix2: \n", decomposed2, end="\n\n" )
# print( "Explained Variance Ratio: ", ??? ) 
print( "Singular Values: ", np.diag( S_prime ) )  # diagonal vector of S

Original Matrix A: 
 [[  0.26374773   2.60321701  -3.95145542  -2.04300905 -12.71632655]
 [-25.9687863    2.89680912  -8.73304644   3.94072657   9.35105544]
 [ -0.15684708   2.59595966 -14.73314241   8.01926596 -17.50752387]
 [ -4.95051931 -10.08600809   0.25244186  -1.21506855 -15.46873182]]

Decomposed Matrix1: 
 [[ 11.09341838  -6.06996015]
 [-20.16078246 -21.30937968]
 [ 16.34305697 -16.28415434]
 [ 11.83087583  -8.12655799]]

Decomposed Matrix2: 
 [[ 11.09341838  -6.06996015]
 [-20.16078246 -21.30937968]
 [ 16.34305697 -16.28415434]
 [ 11.83087583  -8.12655799]]

Singular Values:  [30.60369609 28.67313561]


### TruncatedSVD via sci-kit learn

sci-kit learn library를 이용하면 간단하게 구할 수 있다. 

In [7]:
from sklearn.decomposition import TruncatedSVD

svd = TruncatedSVD( n_components=2, n_iter=10, random_state=42 )
decomposed_skl = svd.fit_transform( A )

print( "Original Matrix A: \n", A, end="\n\n" )
print( "Decomposed Matrix: \n", decomposed_skl, end="\n\n" )
print( "Explained Variance Ratio: ", svd.explained_variance_ratio_ ) 
print( "Singular Values: ", svd.singular_values_ )  # diagonal vector of S


Original Matrix A: 
 [[  0.26374773   2.60321701  -3.95145542  -2.04300905 -12.71632655]
 [-25.9687863    2.89680912  -8.73304644   3.94072657   9.35105544]
 [ -0.15684708   2.59595966 -14.73314241   8.01926596 -17.50752387]
 [ -4.95051931 -10.08600809   0.25244186  -1.21506855 -15.46873182]]

Decomposed Matrix: 
 [[-11.09341838   6.06996015]
 [ 20.16078246  21.30937968]
 [-16.34305697  16.28415434]
 [-11.83087583   8.12655799]]

Explained Variance Ratio:  [0.68164525 0.12224341]
Singular Values:  [30.60369609 28.67313561]


## 5. Bonus


### 1. SVD via NumPy

In [8]:
import numpy as np
U, s, Vh = np.linalg.svd( A, full_matrices=True )
print( U.shape, s.shape, Vh.shape )

(4, 4) (4,) (5, 5)


In [9]:
s_mat = np.zeros( A.shape, dtype=complex)
s_mat[ :s.shape[0], :s.shape[0] ] = np.diag( s )

In [10]:
reconstructed1 = np.dot( U, np.dot(s_mat, Vh ))
reconstructed2 = np.dot( np.dot(U, s_mat), Vh )

print( "Original Matrix A: \n", A, end="\n\n" )
print( "ReConstructed Matrix: \n", reconstructed1, end="\n\n" )
print( "ReConstructed Matrix: \n", reconstructed2, end="\n\n" )

Original Matrix A: 
 [[  0.26374773   2.60321701  -3.95145542  -2.04300905 -12.71632655]
 [-25.9687863    2.89680912  -8.73304644   3.94072657   9.35105544]
 [ -0.15684708   2.59595966 -14.73314241   8.01926596 -17.50752387]
 [ -4.95051931 -10.08600809   0.25244186  -1.21506855 -15.46873182]]

ReConstructed Matrix: 
 [[  0.26374773+0.j   2.60321701+0.j  -3.95145542+0.j  -2.04300905+0.j
  -12.71632655+0.j]
 [-25.9687863 +0.j   2.89680912+0.j  -8.73304644+0.j   3.94072657+0.j
    9.35105544+0.j]
 [ -0.15684708+0.j   2.59595966+0.j -14.73314241+0.j   8.01926596+0.j
  -17.50752387+0.j]
 [ -4.95051931+0.j -10.08600809+0.j   0.25244186+0.j  -1.21506855+0.j
  -15.46873182+0.j]]

ReConstructed Matrix: 
 [[  0.26374773+0.j   2.60321701+0.j  -3.95145542+0.j  -2.04300905+0.j
  -12.71632655+0.j]
 [-25.9687863 +0.j   2.89680912+0.j  -8.73304644+0.j   3.94072657+0.j
    9.35105544+0.j]
 [ -0.15684708+0.j   2.59595966+0.j -14.73314241+0.j   8.01926596+0.j
  -17.50752387+0.j]
 [ -4.95051931+0.j -10.08

In [11]:
dim = 2
U_prime = U[:, :dim]
S_prime = S[ :dim, :dim ]
decomposed = np.dot( U_prime , S_prime )
print( "Decomposed Matrix: \n", decomposed, end="\n\n" )


Decomposed Matrix: 
 [[-11.09341838   6.06996015]
 [ 20.16078246  21.30937968]
 [-16.34305697  16.28415434]
 [-11.83087583   8.12655799]]



### 2. Approch via eigenvalue and eigenvector

In [12]:
import numpy as np

data_1 = np.array([
    [3,1,1],
    [-1,3,1]
])

w_1_1 = data_1.dot( data_1.T )
eig_value_1_1, eig_vector_1_1 = np.linalg.eigh( w_1_1 )

w_1_2 = data_1.T.dot( data_1 )
eig_value_1_2, eig_vector_1_2 = np.linalg.eigh( w_1_2 )


In [13]:
print("Original Data: \n", data_1, end="\n\n" )
print("dot( A, A.T ) Eigen Value: \n", eig_value_1_1, end="\n\n" )
print("dot( A, A.T ) Eigen Vector: \n", eig_vector_1_1, end="\n\n" )
print("dot( A.T, A ) Eigen Value: \n", eig_value_1_2, end="\n\n" )
print("dot( A.T, A ) Eigen Vector: \n", eig_vector_1_2, end="\n\n" )


Original Data: 
 [[ 3  1  1]
 [-1  3  1]]

dot( A, A.T ) Eigen Value: 
 [10. 12.]

dot( A, A.T ) Eigen Vector: 
 [[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]

dot( A.T, A ) Eigen Value: 
 [-2.25970772e-15  1.00000000e+01  1.20000000e+01]

dot( A.T, A ) Eigen Vector: 
 [[-1.82574186e-01  8.94427191e-01 -4.08248290e-01]
 [-3.65148372e-01 -4.47213595e-01 -8.16496581e-01]
 [ 9.12870929e-01  2.77555756e-16 -4.08248290e-01]]



In [14]:
# Sort the eigen vector via the eigen value ranks

idx_1_1 = eig_value_1_1.argsort()[::-1]
eig_value_1_1 = eig_value_1_1[idx_1_1]
eig_vector_1_1 = eig_vector_1_1[:, idx_1_1 ]

idx_1_2 = eig_value_1_2.argsort()[::-1]
eig_value_1_2 = eig_value_1_2[idx_1_2]
eig_vector_1_2 = eig_vector_1_2[:, idx_1_2 ]


In [15]:
print("dot( A, A.T ) Eigen Value: \n", eig_value_1_1, end="\n\n" )
print("dot( A, A.T ) Eigen Vector: \n", eig_vector_1_1, end="\n\n" )
print("dot( A.T, A ) Eigen Value: \n", eig_value_1_2, end="\n\n" )
print("dot( A.T, A ) Eigen Vector: \n", eig_vector_1_2, end="\n\n" )

dot( A, A.T ) Eigen Value: 
 [12. 10.]

dot( A, A.T ) Eigen Vector: 
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

dot( A.T, A ) Eigen Value: 
 [ 1.20000000e+01  1.00000000e+01 -2.25970772e-15]

dot( A.T, A ) Eigen Vector: 
 [[-4.08248290e-01  8.94427191e-01 -1.82574186e-01]
 [-8.16496581e-01 -4.47213595e-01 -3.65148372e-01]
 [-4.08248290e-01  2.77555756e-16  9.12870929e-01]]



In [16]:
# Compare the eigen vectors and see if their non zero elements are equal
rows_1_1 = np.nonzero( eig_value_1_1 )
rows_1_2 = np.nonzero( eig_value_1_2 )
non_zero_1_1 = eig_value_1_1[rows_1_1].copy()
non_zero_1_2 = eig_value_1_2[rows_1_2].copy()


In [17]:
print( rows_1_1 )
print( rows_1_2 )
print( non_zero_1_1 )
print( non_zero_1_2 )

(array([0, 1], dtype=int64),)
(array([0, 1, 2], dtype=int64),)
[12. 10.]
[ 1.20000000e+01  1.00000000e+01 -2.25970772e-15]


In [18]:
U_1 = eig_vector_1_1
temp = np.diag( np.sqrt( non_zero_1_1 ) )
S_1 = np.zeros_like( data_1 ).astype( np.float64 )
S_1[ :temp.shape[0] , :temp.shape[1] ] = temp
V_1 = eig_vector_1_2.T

In [19]:
print( "Created Matrix U: \n", U_1, end="\n\n" )
print( "Created Matrix S: \n", S_1, end="\n\n" )
print( "Created Matrix V: \n", V_1, end="\n\n" )

Created Matrix U: 
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

Created Matrix S: 
 [[3.46410162 0.         0.        ]
 [0.         3.16227766 0.        ]]

Created Matrix V: 
 [[-4.08248290e-01 -8.16496581e-01 -4.08248290e-01]
 [ 8.94427191e-01 -4.47213595e-01  2.77555756e-16]
 [-1.82574186e-01 -3.65148372e-01  9.12870929e-01]]



In [20]:
reconstructed_1 = np.dot(U_1, S_1).dot(V_1)


In [21]:
print("Original Matrix: \n", data_1, end="\n\n" )
print("Recunstructed Matrix: \n", reconstructed_1, end="\n\n" )

Original Matrix: 
 [[ 3  1  1]
 [-1  3  1]]

Recunstructed Matrix: 
 [[-3. -1. -1.]
 [ 1. -3. -1.]]

