# Softmax Classifier

* [모두를 위한 머신러닝/딥러닝 강의](https://hunkim.github.io/ml/)
  - [lab-06-1-softmax_classifier.py](https://github.com/hunkim/DeepLearningZeroToAll/blob/master/lab-06-1-softmax_classifier.py)

In [1]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

In [4]:
X = tf.placeholder( "float", [None, 4] )
Y = tf.placeholder( "float", [None, 3] )
nb_classes = 3

W = tf.Variable( tf.random_normal( [4, nb_classes ] ), name='weight' )
b = tf.Variable( tf.random_normal( [nb_classes] ), name='bias' )

# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax( tf.matmul(X, W) + b ) 
cost = tf.reduce_mean( -tf.reduce_sum( Y * tf.log( hypothesis ), axis=1 ) )
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)



In [5]:
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

In [6]:
# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(2001):
            _, cost_val = sess.run([optimizer, cost], feed_dict={X: x_data, Y: y_data})

            if step % 200 == 0:
                print(step, cost_val)

    print('--------------')
    # Testing & One-hot encoding
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(a, sess.run(tf.argmax(a, 1)))

    print('--------------')
    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, sess.run(tf.argmax(b, 1)))

    print('--------------')
    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, sess.run(tf.argmax(c, 1)))

    print('--------------')
    all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(all, sess.run(tf.argmax(all, 1)))

0 9.560878
200 0.4836745
400 0.37861392
600 0.28513408
800 0.23405674
1000 0.21146592
1200 0.19290088
1400 0.17731398
1600 0.1640239
1800 0.15255243
2000 0.14254999
--------------
[[1.8280901e-03 9.9816245e-01 9.5673868e-06]] [1]
--------------
[[0.90748626 0.07899641 0.0135173 ]] [0]
--------------
[[5.9734080e-09 2.7537701e-04 9.9972457e-01]] [2]
--------------
[[1.8280901e-03 9.9816245e-01 9.5673868e-06]
 [9.0748626e-01 7.8996405e-02 1.3517295e-02]
 [5.9734080e-09 2.7537701e-04 9.9972457e-01]] [1 0 2]
